# Site settings
title: The Digon Games Blog
email: info@digongames.com
description: > # this means to ignore newlines until "baseurl:"
  The thoughts and ramblings of Digon Games' staff. Here we write about
  whatever we please, such as programming, marketing or design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.digongames.com" # the base hostname & protocol for your site
twitter_username: digongames
github_username:  digongames

# Build settings
markdown: kramdown

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
